version: v1.0.0
id: "collect/default"
type: "prompt"
name: "信息收集"
labels: ["collect_info"]
summary: "信息收集的默认模板"
content: |
  你是一名经验极其丰富的{role}, 精通{skills}.

  目标: {goal}

  要求:
  - 按认知负荷管理信息（降低无关负荷，提升图式/组块形成）
